### ISSUE TITLE
i18n not showing default locale

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-app#1020]
*Platform:* All

**Repro:**
1. Add `{{ 'No Data available' | i18n }}` to HTML
2. Change `No Data available` value in `/locale/en_US/mobile-appmaker.json` to `No data has been stored yet!`

**Expected:** "No data has been stored yet!" shows up in rendered template.
**Actual:** "No Data available" shows up.

**Comment by alicoding** [comment]
I'll take a look into this, but FYI you should change in webmaker-app.json not mobile-appmaker.json

**Comment by gvn** [comment]
I don't see `webmaker-app.json` in the repo...

https://github.com/mozilla/webmaker-app/tree/master/locale/en_US

**Comment by alicoding** [comment]
Oops! I thought I did update both on Transifex and here.

**Comment by alicoding** [comment]
I have no clue right now what is the problem here, but this is what I've narrowed it down to.
The problem is in `gulp/locale.js` where is compiling all locales into one file in `locale/index.js`

So, for some reason if I add that key it won't get compile in gulp, but I did the same in node console and it's working fine.

I'm going to spend some time looking at this again to see what is really the problem, but to unblock (if this is really blocking you) change the key name with number infront it will make it visible for now (Please note this is just a workaround and I will try to find a permanent fix soon).

**Comment by alicoding** [comment]
Took me forever to know what was the problem here!

https://github.com/mozilla/webmaker-app/blob/master/locale/en_US/mobile-appmaker.json#L62-L65 this is why!

**Comment by alicoding** [comment]
Verified that this is not an issue anymore.

**Comment by gvn** [comment]
:+1:
