### ISSUE TITLE
Sharing doesn't work for ffos

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1152]
It looks like ffos is trying to use the SocialSharing plugin instead of bypassing it and using sms instead:

This is the error on a publish:
```
"The injected error callback of 'share' received: "Missing Command Error"" SocialSharing.js:88
```

**Comment by k88hudson** [comment]
Hm, yeah, looks like cordova is trying to install it for FFOS. It shows up in the ffos.json file

**Comment by thisandagain** [comment]
Hmm. Ok... will take a look.

**Comment by thisandagain** [comment]
Even though the plugin does not include support for Firefox OS, the `cordova` prepare process is adding the following to the `./plugins/firefoxos.json` file:

```json
{
        "nl.x-services.plugins.socialsharing": {
            "PACKAGE_NAME": "org.mozilla.beaker"
        }
}
```

**Comment by thisandagain** [comment]
To resolve this it looks like we have three options:
Gross – http://stackoverflow.com/questions/23108342/install-cordova-plugin-for-one-platform-only
Clean / Huge Lift – Fix the issue within the `cordova` CLI itself
Hack – User agent detect rather than feature detect within the app

I'm leaning towards option 3.

**Comment by thisandagain** [comment]
I went with 3. :wink:
