### ISSUE TITLE
Stop deploying web version without cordova wrapper

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1251]
A lot of confusion has come out of people testing on the web links. Once we merge cordova/webmaker-app we should either:

a. remove the web version entirely
b. only deploy a cordova-wrapped web version, and if we do, we should put a note on it somewhere prominently that it's not full-featured

Personally I'm more in favour of b.

**Comment by thisandagain** [comment]
:+1: I suggest option `a` as having community, staff, and volunteers continue to test and submit bugs against a web version isn't particularly helpful for us. My instinct is that due to the reduced friction and our history / "who we are", users will have a strong tendency to go towards a web version even if it is not full-featured.

/cc @jbuck

**Comment by jbuck** [comment]
Yeah, I'd argue that we should move towards a as well.

**Comment by k88hudson** [comment]
Good points. I think I would feel much better about `a` if we do more work on the developer experience on the cordova side (@jbuck's patch will already help a lot)

**Comment by Pomax** [comment]
If we can make development painless, then I'm all for option (a). However, that does require it's going to have to be possible to do things like checking currently applied CSS, running JS against the current state, and wrecking the active DOM. If that stays possible, hurray. If not, (a) isn't a real option.
