### ISSUE TITLE
Android - Phone brick does not open phone on tap

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1269]
*OS:* Android 5.0

**Repro Steps:**
1. Open app w/ Phone brick
2. Tap phone brick to place call

**Expected:** Phone app opens w/ phone number pre-populated
**Actual:** Nothing happens

**Comment by Pomax** [comment]
test results (wip):
- [x] Opening the app "in firefox" and pressing the phone button pops up a correctly prepopulated phone app.
- [ ] Opening the app in webmaker-app and pressing the phone button pops up a correctly prepopulated phone app.

**Comment by Pomax** [comment]
it strongly looks like this is entirely by design - in a published app, the phone and SMS button work fine (i,e, publish app, open in FF in android, press button -> phone/sms apps open with prefilled text).

However, in the design view, we don't have the "real" elements, we have generic elements with the right tag, and (technically illegal) properties that map to the brick properties, so for instance a real phone brick is
```
<button onclick={tied to the click handler by vue}>phone label</button>
```
but the editor view element that we generate is:
```
<button style="background-color: #64A8EE" innerhtml="Call Campus Safety" number="+18005555555">Call Campus Safety</button>
```

**Comment by Pomax** [comment]
That was a wonderful journey deep into code. What actually goes wrong: 

- we create phone bricks using the Vue definition in index.js
- when rendered to the page, Vue triggers .created and we add the onClick handler
- things work!
- except they don't because we don't render the original block to the page, we clone it various times using the node `clone` module.
- that module will deep copy an object including its functions
- but... only *prototype* functions, not closure-wrapped instance functions
- so we end up with buttons that do nothing.

The fix involved moving the onClick handling out of the lifecycle function and instead making it a general prototype function by using Vue's `methods` block (similar in function to `attributes` and `data`), which then ensures there is a prototype for `clone()` to copy, preserving behaviour based on function calls.
