### ISSUE TITLE
Review supported languages

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1281]
Let's have a look at the list of supported languages in the app, and check them for quality. Specifically, it would be good to have a reviewers who are:

a. a native speaker;
b. able to test on Android or Firefox OS (either is fine)

For MWC, let's fine people who can do this for 

* [x] French
* [x] Bangla
* [x] Hindi

We should ask them to run through all the views of the app (including the install page), using:

* [x] Link to QA script:

@secretrobotron can you help fill in these blanks?

@davidascher can you help us do QA for French?

**Comment by secretrobotron** [comment]
> let's fine people

Email request sent.

> Link to QA script

Will develop today.

**Comment by secretrobotron** [comment]
### Splash Page
*http://webmaker.org/app (http://webmaker.mofostaging.net/app)*
- Does the copy on the page make sense to you?
  - Are instructions clear?
  - Are there grammar/spelling mistakes?
- Click the install button and proceed to the next step

### Install Page
*http://mzl.la/installwm*
- If you happen to see text on this page, does it make sense?

### In-app
- Make sure your phone's locale settings reflect the language you want to see
  - Otherwise, go to "My Apps", hold the title bar for 5 seconds to reveal the "Developer Health Check"
  - Scroll to the bottom, and change the language setting

##### "My Apps" Tab
- Make sure the "privacy" and "legal" links are translated
- If you don't have any apps yet, make sure the message is translated and provides clear instruction

##### "Make" Tab
- Are all of the options translated and representative of their content?
- Try "Start from Scratch"
  - Make sure the toucan's messages are translated and provide clear instructions
- Click on the "+" button
  - Make sure the toucan is sane
  - Try all of the options and make sure they are translated, and make sense
- Click on the gear icon to edit app settings
  - Make sure this page is translated and makes sense
- Try publishing your app
  - Make sure the "Publishing" message appears in your language
  - Turn on airplane mode, and try publishing again
  - Make sure the publishing error message appears in your language
- Try deleting your app
  - Make sure the warning message makes sense

##### "Discover" Tab
- Make sure the sub-nav ("Featured" / "Newest") is clear
- Make sure that the each entry has been translated appropriate (specifically, the "by Guest" part)

**Comment by thisandagain** [comment]
Is this good to close @secretrobotron ?
