### ISSUE TITLE
Alias locales for which Android doesn't have specifics

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-app#1310]
If a user's locale is bn-bd or bn-in, google reduces both to just "bn" on Android. Webmaker app doesn't choose the correct locale because we have "bn-bd".

We need a alias for bn-XX -> bn. Or, simply bn-bd to bn for now.

@thisandagain ok to route bn-in to bn as well?

**Comment by secretrobotron** [comment]
@thisandagain going to just use the advice from https://github.com/mozilla/webmaker-app/issues/780#issuecomment-74159757. :+1:

**Comment by secretrobotron** [comment]
This happens on FirefoxOS as well.

**Comment by k88hudson** [comment]
Ok, I think this is how we should approach saving/not saving locale:

* rename `data.session.locale` to `data.session.localePreference`
* when we initialize the locale stuff, set a property on the locale object (in memory) called `currentLocale` to `data.session.localePreference` if it is set, otherwise use autodetection
* by default, the language picker should be set to `Use device default`. Choosing this will clear the value from `data.session.localePreference`, and set the `currentLocale` using autodetection
* if a user sets the language picker to something other than the browser default, set `data.session.localePreference`  and update `currentLocale`
