### ISSUE TITLE
Regressions from styling

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-app#1434]
These problems appear to have been introduced post `7c493bdcbbab72ae9c738e5ad5eca33560187ff5`

- Can't change app icon or color
  1. Create or open existing app
  2. Click gear icon
  3. Try to click color swatches or back/forward arrows next to icon

- Can't re-order blocks ("`Uncaught TypeError: Cannot read property '_onSync' of undefined`" storage.js - 162)
  1. Create or open existing app
  2. Click pencil icon on block
  3. Click up or down arrow (error is thrown in console)
  4. Navigate back
  5. See that changes haven't persisted

**Comment by Pomax** [comment]
The refactors that were performed on the `App` object seems to have caused breakage for which we have no test coverage. If we can get STR that highlight each of these problems we can turn these into unit tests for running as part of the test tasks, so that when we fix this we'll never run into this regressing again.

**Comment by Pomax** [comment]
Our unit test mock firebase is lacking implementations of the `once` and `set` functions, so it turns out we actually can't test whether App behaves at all. Fixing that as part of this bug, or we won't have any reliable App unit tests.
