### ISSUE TITLE
UX for Zoom out

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1495]
Testing the play experience with content quickly revealed the need to zoom out beyond the current 3-across view. http://jsbin.com/yoqici

On desktop, this won't be a problem. On mobile this could be solved with pinch-to-zoom if it performs. Or, a second tap of the zoom-out icon might be required. 

UX Questions
 - does it include the full project? or, the smallest size that allows for adding and moving tiles. 
 - does double-tap and zoom go directly to page view?
 - what are reasonable page limits for horizontally or vertically oriented projects?

**Comment by flukeout** [comment]
Current assumption lives here:
http://flukeout.com/examples/tiles-nav-2/index.html

* Fully zoomed out view zooms out until the pages are smallest reasonable touch targets
* Single-tap zooms in during Play Mode

**Comment by xmatthewx** [comment]
Interesting
 - transitions/animations feel great
 - single-tap feels nice for playing a project. we will need to see if it confuses authors who become familiar with double-tap. 
  - we need a subtle sound effect for taps and zooms. 
 - ultra-zoom-out - would be nice if it only goes as far as necessary within the limit that you set. so a 5x5 project fills the screen.  not essential, but could be nice.

**Comment by flukeout** [comment]
*  Agreed on ultra zoom out, should only go out as far as necessary and stop zooming out at a certain cut-off.
* With single tap to zoom, the blue border seems way less important since nothing is really ever 'selected' - it's just remembered for the next time you zoom in - I'd like to try a different treatment, like an icon maybe.
* Also wondering about panning, should we limit panning to the content bounds? I think like we may want to.

**Comment by xmatthewx** [comment]
I think we can call this done. True? Documented on [two slides](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gae931fbd6_7_20) in the build deck for Play and Editor.
