### ISSUE TITLE
Research options for front-end monitoring

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#423]
We might be able to do this with Newrelic, but AFAIK it doesn't work very well with client-side rendering/routing and depends on a server endpoint.

What about using google analytics?

@thisandagain @simonwex

**Comment by adamlofting** [comment]
Here are my thoughts so far:

* To back-date analytics data when a user comes back online, we have to use GA's [Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/) rather than the default [Web Tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/)
  * I haven't seen a JS based wrapper for this yet (though this has been done in plenty of other languages)
* To do this we would build our own equivalent of GA's tracker object as used for an analytics.js implementation
  * We could possibly extend webmaker-analytics, or this might be better as a new module
* We can and should make use of a bunch of the [app specific analytics parameters](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#apptracking) (recording app version, and screenviews specifically)
* We should use the [Exceptions tracking](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#exception) function of UA to keep an eye on app error rates
* We replace the standard GA script currently in the footer of index.html with our new tracker script
* The new tracker script checks for connectivity before processing data that has been queued, otherwise it adds events to the queue.
  * The queue is a really simple array, localeForage should be easy to use for this without needing a more advanced queue library.
* We might need to write some modifications to handle Cordova apps (but this might not apply to the Measurement Protocol - TBC) http://stackoverflow.com/questions/27561676/how-do-i-configure-my-google-analytics-account-to-accept-requests-from-file-u
* We'll need to rely on a locally set UUID rather than cookies. I spotted we have this for Guest Users already in the app.
* We should track locales using custom variables
* We'll then need to add the view, event and error tracking throughout the app

--
@thisandagain @k88hudson - is this sounding sane? Or raising alarm bells?

If we're on the right track, I'll work on building it this week.

**Comment by thisandagain** [comment]
Follow-up from meeting this morning:
:+1: Sounds great. I'd prefer to use the UUID provided by Firebase.

**Comment by davidascher** [comment]
@brianleroux might have some insight w.r.t. cordova specifically.

**Comment by k88hudson** [comment]
Sounds like a great start. Thanks for looking into this @adamlofting

**Comment by adamlofting** [comment]
I've started on an implementation and opened a PR here:
https://github.com/mozilla/webmaker-app/pull/904

Shall we close this 'research...' ticket now?

**Comment by brianleroux** [comment]
/me waves!

not entirely sure how/what is going on here but super happy to set aside some time and share any cordova related junk I might know =P

**Comment by adamlofting** [comment]
Thanks @brianleroux! This ended up being implemented at an app level rather than the cordova level but we might yet find some cordova related questions as we test this further. 

All: I'm going to close this "research" ticket now, and move any further conversation to the implementation (https://github.com/mozilla/webmaker-app/pull/904)
