### ISSUE TITLE
Weird back button functionality

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#545]
I'm noticing a lot of weird back button functionality. A few notes:

- [ ] colour should *always* return to block editor
- [ ] block editor should *always* return to `/edit`
- [ ] when starting the app in `/make/:something`, the back button doesn't work

Also noted:
- [ ] Open Template > Make zero edits > Tap Back > should return to templates

**Comment by Pomax** [comment]
last issue is even more special. Filing #992 for it

**Comment by Pomax** [comment]
root cause here is that the color picker is not itself a view, so while our app "knows" that it has a state to go back to simply by virtua of closing the component and revealing the underlying content, the browser/android/etc back buttons only know that the *actual* view is /block, and will take you back to the app preview even if you're on what feels like a deeper page/view/card/etc.

**Comment by Pomax** [comment]
Filed #997 for the color picker returning.

**Comment by k88hudson** [comment]
this is a dupe now
