### ISSUE TITLE
Add Brick page has wrong title + stylin'

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-app#648]
![image](https://cloud.githubusercontent.com/assets/25212/5511062/1bd891fc-877e-11e4-8823-b8ad0afe8ce9.png)

Should say "Add a brick" or "add content" or something.

**Comment by k88hudson** [comment]
@droxxr sorry for the late reply–we've been on vacation. If you're still up for it, go for it ^_^

**Comment by droxxr** [comment]
I tried it over the break... Though, it's more complicated than I thought to align the elements in the navigationBar horizontally, such that it’s all evenly spaced -- I'm giving it up. Though, here's my attempt, hopefully it'll be some benefit: https://github.com/droxxr/webmaker-app/tree/issue%23648

What I did that can help:

I think there should be two different CSS class styles for the navigationBar element, in order to style it differently for the different views
- E.g. the add view has different font color and background etc.
- Previously we would have to create the html markup for a new navigationBar and additional CSS for the custom navigationBar style
- Now, you just need to add the class to the navigationBar (.navigationBar-default or .navigationBar-alt) to style it based on the type of navigationBar style you want for a view

What I tried in order to align the elements horizontally within the navigationBar:
- line-height -- property to vertically align the title header to the center
- vertical-align: middle -- To horizontally align the buttons and title elements within the navigationBar
- NavigationBar components are inline-block

Draw back:
- Need to use ul list structure

**Comment by gvn** [comment]
Thanks for working on that @droxxr. I'll have a look at your work and see if I can incorporate any of it. Cheers!

**Comment by gvn** [comment]
@k88hudson I have a PR ready for this...see #662

**Comment by gvn** [comment]
@droxxr FYI: I ended up using Flexbox to fix this. Not sure how familiar you are with it, but it's very useful! http://css-tricks.com/snippets/css/a-guide-to-flexbox/ :+1:
