### ISSUE TITLE
Delete button on edit page should match block editor delete button

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#670]
i.e. on `/make/:id` the large red delete button should look like this instead:

![image](https://cloud.githubusercontent.com/assets/1455535/5652482/1009b134-967f-11e4-9643-8d0aa50330e5.png)

**Comment by k88hudson** [comment]
Relevant view file is in `/views/make/index.html`

**Comment by droxxr** [comment]
There some other issues that I've noticed relating to this:

-The "make view" has a 10px left and right padding set to the edit-inner container, which offsets the right and left side of all "button components" within it to 10px, which includes the delete button.

Whereas the "block view" does not have a padding set to the edit-inner container , however all the "button components" have a 15px left and right margin that offsets them within it. So there's some inconsistency.

Should I change all views such that their edit-inner container has the same set 10px or 15px padding. Or should all the "button components" have the same margin 10px or 15px, and the edit-inner container has a 0px padding.

------
I also noticed that the .btn class used for button elements in button.less has the CSS property "display: flex". Apparently, flexbox does not work with button elements (https://bugzilla.mozilla.org/show_bug.cgi?id=984869).

The reason I bring this up is because I would like to create a .btn-delete class for the delete button to be able to use it widely, and right now the CSS code for the delete button is only available within the "block view" index.less.
