### ISSUE TITLE
Add Brick cancel flow

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#956]
As a user new to Webmaker, I'd like to click a brick in the brick selector, view the edit options, and then cancel to return to the selector (rather than the app). 

I believe this is more intuitive and conducive to learning and experimentation. The jump back to the app requires me to click add again. 

This would require a cancel button in the selector view, which would require some new design.

**Comment by thisandagain** [comment]
Major :+1: to this.

**Comment by vazquez** [comment]
Definitely :+1: The selector screen already has a cancel button, we are just not routing it correctly.

![screenshot 2015-02-19 11 35 16](https://cloud.githubusercontent.com/assets/1119821/6270945/787cc8a0-b82b-11e4-89e5-e2003ea12724.png)

**Action:** When a user taps on "Cancel", we need to send them back to the Add Content screen, instead of the Edit screen.

**Comment by alicoding** [comment]
@thisandagain currently if you click on the editor and pick "Text" block then click "Cancel" it will add the block. Is this an expected behaviour? I think it is weird when I click cancel and it's still adding the block for me?

**Comment by thisandagain** [comment]
@alicoding Yikes. That's a bug. Can you file?
